export const VaccineStatus = {
  ELIGIBLE_NOW: "ELIGIBLE NOW",
  DUE_SOON: "DUE SOON",
  OVERDUE: "OVERDUE",
  NOT_ELIGIBLE: "NOT ELIGIBLE",
  COMPLETED: "COMPLETED",
  ONE_DOSE: "ELIGIIBLE FOR ONLY 1 DOSE",
  TWO_DOSE: "ELIGIBLE FOR 2 DOSE",
};

export const DoseEligibility = {
  NONE: "NO DOSE NEEDED",
  ONE_DOSE: "ELIGIIBLE FOR ONLY 1 DOSE",
  TWO_DOSE: "ELIGIBLE FOR 2 DOSE",
};
